#!/bin/sh /etc/rc.common
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

USE_PROCD=1
START=90
STOP=90

PROG="${INSTALL_PREFIX}/bin/dm"
OPENSYNC_DB=${INSTALL_PREFIX}/etc/conf.db.bck
OPENSYNC_SCHEMA=${INSTALL_PREFIX}/etc/opensync.ovsschema
OVS_DB_DIR=/var/run/openvswitch
OVS_DB=/var/run/openvswitch/conf.db
CERTS_DEST_PATH=/var/run/openvswitch/certs
CERTS_SRC_PATH=${INSTALL_PREFIX}/certs

start_service()
{
    ${INSTALL_PREFIX}/bin/reg_dom_update.sh
    procd_open_instance
    echo "Setting certificates"
    mkdir -p ${CERTS_DEST_PATH}
    cp ${CERTS_SRC_PATH}/* ${CERTS_DEST_PATH}/
    ${INSTALL_PREFIX}/bin/start.sh
    echo "Starting OpenSync"
    procd_set_param command ${PROG}
    procd_close_instance
}

stop_service()
{
    echo "Removing certificates"
    rm -rf ${CERTS_DEST_PATH}
    echo "Killing managers"
    killall -9 dm cm nm wm lm sm bm um om qm fsm fcm
    killall -9 udhcpc dnsmasq
    echo "Removing existing DHCP leases"
    rm /tmp/dhcp.leases
    echo "Removing old wpa_ctrl sockets"
    rm -f /tmp/wpa_ctrl_*
    echo "Removing old hostapd and supplicant files"
    rm -r /tmp/run/wpa_supplicant-*
    rm -r /tmp/run/hostapd-*
    echo "Removing DNS files"
    rm -rf /tmp/dns
}
